services:
  mongo:
    container_name: mongo
    image: mongo
    command:
        - --storageEngine
        - wiredTiger
        - --auth
    environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db
    env_file:
        - .env
    networks:
        - mongo-db-network
    restart: unless-stopped
        
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
        - "${ME_CONFIG_DEFAULT_PORT}:8081"
    environment:
        - ME_CONFIG_MONGODB_SERVER=mongo
        - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
        - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
    depends_on:
        - mongo
    env_file:
        - .env
    networks:
        - mongo-db-network
    restart: unless-stopped

networks:
    mongo-db-network:
        driver: bridge

volumes:
  mongo_data: